name: BookStore Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Установка Selenium для возможности запуска функциональных тестов
        # pip install selenium
    
    - name: Run unit tests
      run: |
        python -m unittest test_unit.py
      
    - name: Run integration tests
      run: |
        python -m unittest test_integration.py
    
    # Функциональные тесты отключены в CI, т.к. требуют веб-приложения
    # - name: Run functional tests
    #   run: |
    #     python -m unittest test_functional.py